In [12]:
import numpy as np

matriz = np.array([[1, 0, -1],
                   [2, 0, 2],
                   [8, 2, -3]])

matriz_inversa = np.linalg.inv(matriz)

print('MATRIZ')
print(matriz)
print('-----------------------------------------')
print('MATRIZ INVERSA:')
print(matriz_inversa)

MATRIZ
[[ 1  0 -1]
 [ 2  0  2]
 [ 8  2 -3]]
-----------------------------------------
MATRIZ INVERSA:
[[ 0.5    0.25   0.   ]
 [-2.75  -0.625  0.5  ]
 [-0.5    0.25  -0.   ]]
